spring:
  application:
    name: backend-item
server:
  port: 9011

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/


FTP_HOST: 192.168.9.144
FTP_PORT: 21
FTP_USERNAME: NEXUS
FTP_PASSWORD: NEXUS
FTP_BASEPATH: /HOME/FTPUSER/

tx-lcn:
  client:
    manager-address: 192.168.9.145:8070