spring:
  application:
    name: frontend-cart
server:
  port: 9040

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/


#临时购物车的key
cart_cookie_name: CART_COOKIE_NAME