spring:
  application:
    name: common-item
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bz_shop?characterEncoding=UTF-8
    username: root
    password: 123123
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 9010

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/