spring:
  application:
    name: frontend-search
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bz_shop?characterEncoding=UTF-8
    username: root
    password: 123123
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    solr:
      host: http://192.168.70.158:8080/solr
      core: collection1
server:
  port: 9100

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/