spring:
  application:
    name: frontend-order
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bz_shop?characterEncoding=UTF-8
    username: root
    password: 123123
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 9111

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

tx-lcn:
  client:
    manager-address: 192.168.9.145:8070