spring:
  application:
    name: common-redis
  redis:
    database: 1
    host: 192.168.9.145
    port: 6379
    jedis:
      pool:
        max-active: 200 #最大链接数
        max-wait: -1 #连接池最大等待时间
        max-idle: 10 #连接池最大空闲数
        min-idle: 0
    timeout: 2000 #链接超时时间
server:
  port: 9080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/



tx-lcn:
  client:
    manager-address: 192.168.9.145:8070

#配置缓存首页商品分类的key
frontend_catresult_redis_key: frontend:catresult:redis:key

#配置缓存首页大广告位的key
frontend_ad_redis_key: frontend:ad:redis:key:89

#配置缓存商品基本信息的key
frontend_item_basic_info_key: frontend:item:basic:info:key

#配置缓存商品描述信息的key
frontend_item_desc_info_key: frontend:item:desc:info:key

#配置缓存商品规格参数信息的key
frontend_item_param_item_info_key: frontend:item:param:item:info:key

#配置用户的key
user_session_redis_key: user:session:redis:key

#配置用户购物车的key
frontend_cart_redis_key: frontend:cart:redis:key

#缓存订单id的key
order_item_id_key: order:item:id:key

#订单id的初始值
init_item_id_key: 2000