spring:
  application:
    name: backend-content
server:
  port: 9021

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/



tx-lcn:
  client:
    manager-address: 192.168.9.145:8070